name: SuggestionsTooltipShowcase
version: ${pluginVersion}
main: com.github.fefo.suggestionstooltipshowcase.SuggestionsTooltipShowcase
api-version: 1.16
depend: [ ProtocolLib ]
authors: [ Fefo ]
description: Pog showcase plugin for custom "suggestions tooltips"

commands:
  tooltips-with-protocollib: { }
  tooltips-with-paper-mojangapi: { }
